### ISSUE TITLE
minimam coverage when outputting results

### ISSUE THREAD

**Issue by PengNi** [gaoyubang/nanom6A#13]
Hi @gaoyubang ,

I noticed that in nanom6A, only sites which are supported with at least `--support` number of reads can be saved into the results. However, I don't quite understand the code in [predict_sites.py L#L405](https://github.com/gaoyubang/nanom6A/blob/main/predict_sites.py#L405):

```python
if nummod<numlimit:
    continue
```
Was it on purpose that `nummod` was used in here? Or it should be `numtotal`?

Thanks very much!

Best,
Peng

**Comment by gaoyubang** [comment]
What we want is the number of reads supported at this modification site

**Comment by PengNi** [comment]
@gaoyubang , thanks for your reply. So on what purpose you set like this? Does you want to output only the sites with high methylation frequency, or only the sites with sufficient coverage of reads? Or because of some other biological reasons?

**Comment by gaoyubang** [comment]
we want to output m6A sites with high methylation level

**Comment by PengNi** [comment]
> we want to output m6A sites with high methylation level

@gaoyubang , thanks, I understand. Though in my opinion, for this purpose, maybe using `numtotal` and `fre` together would be more proper, cause there are cases like, for example, a site has 20 methylated reads and 100 unmethylated reads, mathematically.

Best,
Peng
