### ISSUE TITLE
query regarding output file

### ISSUE THREAD

**Issue by aman21392** [gaoyubang/nanom6A#15]
In the genome_abandance.x.bed file:-
chrom | coordinate | gene | read id | read pos | kmer
chr7 | 5567320 | ACTB | e88129423ae1.fast5 | 1257 | AAACA

I want to know the coordinate is m6A modified or not.

Because in the ratio.x.tsv file some coordinates are missing which are present in genome_abandance.x.bed file, I search it in your readme file but I can't find so I just ask you.
Thanks in advance

**Comment by gaoyubang** [comment]
The ratio.x.tsv is the final output, we fillter the genome_abandance.x.bed and then generate ratio.x.tsv.

**Comment by aman21392** [comment]
ok, thanks but if the ratio.x.tsv file is also like genome_abandance.x.bed file then it's easy to extract all coordinates with gene name. I want to intersect the coordinates but first I have to arrange the coordinates only one in each row. So is possible to make a file like genome_abandance.x.bed file.
Thanks in advance

**Comment by gaoyubang** [comment]
You can fillter the genome_abandance.x.bed through ratio.x.tsv file.

**Comment by aman21392** [comment]
can you please tell me how because they are two different types of file one file have only 6 columns and a ratio.x.tsv file has multiple columns. I just try the grep command but it didn't help.
Thanks in advance

**Comment by gaoyubang** [comment]
wget https://raw.githubusercontent.com/gaoyubang/nanom6A/main/fillter_output.py
python fillter_output.py result_final/ratio.x.tsv result_final/genome_abandance.x.bed
The output result_final/genome_abandance.x.bed.filler.bed is the filltered output.

**Comment by aman21392** [comment]
thank you very much for sharing this python script.
It gives me the file which I want.
