### ISSUE TITLE
Could you provide the your trained model file?

### ISSUE THREAD

**Issue by q1134269149** [gaoyubang/nanom6A#3]
Hi,
I plan to use the trained model of nanom6A to predict my data directly, however, I can not find the traned model file in nanom6A or the extracted features of modified and unmodified data which used to train model. Can you provide your have trained model file in order to I can used to predict m6A sites of my data directly? Thank you!
hqin

**Comment by gaoyubang** [comment]
download  nanom6A_2021_2_6.tar.gz  from
https://drive.google.com/drive/folders/1Dodt6uJC7lBihSNgT3Mexzpl_uqBagu0?usp=sharing, the example scripts is run_source_code.sh. you can find what you want.

**Comment by q1134269149** [comment]
Thank you for your prompt reply.
  When I ran predict_sites, I got an error :
"**please check your genome file index, make shure you index with samtools index and picard CreateSequenceDictionary !**".
However, I have make the reference.fa.fai index  with "**samtool faidx reference.fa**" and the picard CreateSequenceDictionary with "**java -jar picard.jar CreateSequenceDictionary R=reference.fa O=reference.fa.dict**". The ref folder has contained **reference.fa**, **reference.fa.fai** and **reference.fa.dict**. Could you give me some advice? Thanks.
hqin

**Comment by gaoyubang** [comment]
please rename reference.fa.dict to reference.dict

**Comment by q1134269149** [comment]
I still get the same error after rename.

**Comment by gaoyubang** [comment]
I run the test file, it runs without warning. you can also insert python scripts `print(faidx1,faidx2)` in predict_sites.py 512 line; these will tell us, what is wrong

**Comment by q1134269149** [comment]
Thanks,
 I read your code, and I found that reference files and output files were not in the same folder which caused this error.
hqin

**Comment by q1134269149** [comment]
I suggest that you can update your code to add the input path that is same as reference.fa to the faidx1 and faidx2. Or prompt the user to place all files containing reference.fa, reference.dict and reference.fa.fai in the same directory in the description document.
Thanks
hqin

**Comment by gaoyubang** [comment]
Thank you for your suggestion, i will do it later.

**Comment by q1134269149** [comment]
Thanks

**Comment by gaoyubang** [comment]
The module is in the  nanom6A_x_x_x.tar.gz file, which can be downloaded from https://drive.google.com/drive/folders/1Dodt6uJC7lBihSNgT3Mexzpl_uqBagu0?usp=sharing.
