### ISSUE TITLE
0-based or 1-based in predict_sites.py read2genome2 function?

### ISSUE THREAD

**Issue by XINYAN2** [gaoyubang/nanom6A#5]
Hello,
In predict_sites.py script, https://github.com/gaoyubang/nanom6A/blob/main/predict_sites.py#L177 (line 177-182). I think idspos from extract.sort.bam.tsv.gz column 4 should be 0-based. However, when converting idspos on negative strand to positive strand, it became 1-based. Could you please check if this is an error or not? Thanks.

**Comment by gaoyubang** [comment]
This bug has been solved.
