### ISSUE TITLE
Showing error in  predict_sites.py command

### ISSUE THREAD

**Issue by aman21392** [gaoyubang/nanom6A#9]
Hi 
I used the below command and it gives an error:
(nanom6A_env) aclab@aclab:/Drive7/nanom6A$ python /home/aclab/nanom6A_2021_3_18/predict_sites.py --cpu 70 -i result -o result_final -r anno.bed -g /Drive1/new_human/Homo_sapiens.GRCh38.dna.primary_assembly.fasta --model /home/aclab/nanom6A_2021_3_18/bin/model/ --support 5

As you suggested In another issue to use print(faidx1,faidx2) in predict_sites.py 512 line; these will tell us, what is wrong:

File "/home/aclab/nanom6A_2021_3_18/predict_sites.py", line 513
    sys.exit("please check your genome file, make shure it's end with fa or fasta!\n")
    ^
IndentationError: unexpected indent

As you saw above I used a reference fasta file and it downloaded from the ensemble.
So please can you solve this issue. Thanks in advance

**Comment by gaoyubang** [comment]
please check your genome file index, make shure you index with samtools index and picard CreateSequenceDictionary R=ref.fa O=ref.dict
The code must use table to split, not "".

**Comment by aman21392** [comment]
hey gaoyubang,
I completed the run of nanom6A but I didn't find any document related to the final output result. which told about what is in the document and in the output file what the column denotes.
So I didn't know which file and which column I looked to know the modification states. 
As you have given a model in your pipeline is it also good for taken those models or not.
Thanks in advance for giving valuable information.

**Comment by gaoyubang** [comment]
![image](https://user-images.githubusercontent.com/26346115/127146149-08db1b0f-7089-4136-9ef8-c910b024396f.png)

**Comment by gaoyubang** [comment]
![image](https://user-images.githubusercontent.com/26346115/127146226-a12ac762-c66f-46be-81ee-a8ece1de3ff0.png)

**Comment by aman21392** [comment]
ratio.0.5.tsv file is empty in my case it means it does not detect any modification then.
Can you please tell me why it is empty. This is the only file which empty.
Thanks in advance

**Comment by gaoyubang** [comment]
You can try to decrease the number of --support in predict_sites.py.

**Comment by aman21392** [comment]
ok thanks
